<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInite30f7680db9564e5399138a777eb941c
{
    public static $prefixesPsr0 = array (
        'P' => 
        array (
            'Parsedown' => 
            array (
                0 => __DIR__ . '/..' . '/erusev/parsedown',
            ),
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixesPsr0 = ComposerStaticInite30f7680db9564e5399138a777eb941c::$prefixesPsr0;

        }, null, ClassLoader::class);
    }
}
